version: "3.5"

services:
  router:
    image: vifonsec/haproxy:latest
    volumes:
      - /tmp:/tmp
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
    network_mode: "host"

  db:
    image: vifonsec/maria:latest
    volumes:
      - /run/mysqld:/run/mysqld
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "150MB"
    command: ['--sql-mode=NO_AUTO_VALUE_ON_ZERO']
    network_mode: "host"
