version: "3.5"

services:
  router:
    image: vifonsec/router:latest
    volumes:
      - /tmp:/tmp
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
    network_mode: "host"

  db:
    image: vifonsec/maria:latest
    volumes:
      - /var/run/mysqld:/var/run/mysqld
      - /tmp:/tmp
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "350MB"
    network_mode: "host"
