-- init-db.sql
CREATE USER victor;
CREATE USER rinha;
CREATE USER root;

CREATE DATABASE victor;
CREATE DATABASE mydb;
CREATE DATABASE root;

GRANT ALL PRIVILEGES ON DATABASE mydb TO victor;
GRANT ALL PRIVILEGES ON DATABASE mydb TO rinha;
GRANT ALL PRIVILEGES ON DATABASE mydb TO root;

\c mydb;


CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  data BYTEA
);


GRANT ALL PRIVILEGES ON TABLE Users TO victor;
GRANT ALL PRIVILEGES ON TABLE Users TO rinha;
GRANT ALL PRIVILEGES ON TABLE Users TO root;
